config/routes.rb
Blog::Application.routes.draw do      
  
  get "admin_sessions/new"

  resource :admin_session
  resources :admins
  resources :posts
  
  match "/register" => "admins#new", :as => :register
  match "/sign-in" => "admin_sessions#new", :as => :sign_in
  match "/sign-out" => "admin_sessions#destroy", :as => :sign_out

  root :to => 'posts#index'
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  acts_as_authentic do |c|
      c.login_field = :name
    end 
  has_many :posts
     
end

app/models/admin_session.rb
class AdminSession < Authlogic::Session::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :admin
end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController
  def new
    @admin_session = AdminSession.new
  end

  def create
    @admin_session = AdminSession.new(params[:admin_session])
    
    if @admin_session.save
      flash[:notice] ="You have successfully logged in."
      redirect_to posts_url
    else
      render :action => :new
    end
  
  end  
  
  def destroy
    current_admin_session && current_admin_session.destroy
    flash[:notice]  = "You are now logged out." 
    redirect_to posts_url
  end  
     
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  # GET /admins
  # GET /admins.xml
  def index
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admins }
    end
  end

  # GET /admins/1
  # GET /admins/1.xml
  def show
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin }
    end
  end

  # GET /admins/new
  # GET /admins/new.xml
  def new
    @admin = Admin.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin }
    end
  end

  # GET /admins/1/edit
  def edit
    @admin = Admin.find(params[:id])
  end

  # POST /admins
  # POST /admins.xml
  def create
    @admin = Admin.new(params[:admin])

    respond_to do |format|
      if @admin.save
        format.html { redirect_to(@admin, :notice => 'Admin was successfully created.') }
        format.xml  { render :xml => @admin, :status => :created, :location => @admin }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admins/1
  # PUT /admins/1.xml
  def update
    @admin = Admin.find(params[:id])

    respond_to do |format|
      if @admin.update_attributes(params[:admin])
        format.html { redirect_to(@admin, :notice => 'Admin was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.xml
  def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy

    respond_to do |format|
      format.html { redirect_to(admins_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_admin_session, :current_admin
  
  private 
  
  def current_admin_session
    return @current_admin_session if defined?(@current_admin_session)
    @current_admin_session = AdminSession.find
  end
  
  def current_admin
    return @current_admin if defined?(@current_admin)
    @current_admin = current_admin_session && current_admin_session.admin
  end   
  
  def require_current_admin
    unless current_admin
     flash[:error] = 'You must be logged in.' 
      redirect_to root_path
    end  
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_current_admin, :except => [:index, :show]
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin_sessions/new.html.haml
%h2 Sign In

= form_for @admin_session, :url => admin_session_path do |f|
  -if @admin_session.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_session.errors.count, "error")} prohibited this admin from being saved:"
      %ul
        - @admin_session.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.submit 'Submit'

app/views/admins/_form.html.haml
= form_for @admin do |f|
  -if @admin.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin.errors.count, "error")} prohibited this admin from being saved:"
      %ul
        - @admin.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/admins/edit.html.haml
%h1 Editing admin

= render 'form'

= link_to 'Show', @admin
\|
= link_to 'Back', admins_path

app/views/admins/index.html.haml
%h1 Listing admins

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @admins.each do |admin|
    %tr
      %td= admin.name
      %td= link_to 'Show', admin
      %td= link_to 'Edit', edit_admin_path(admin)
      %td= link_to 'Destroy', admin, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Admin', new_admin_path

app/views/admins/new.html.haml
%h1 New admin

= render 'form'

= link_to 'Back', admins_path

app/views/admins/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @admin.name

= link_to 'Edit', edit_admin_path(@admin)
\|
= link_to 'Back', admins_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
  %title mewie.com blog
  = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Allerta', :rel => 'stylesheet', :type => 'text/css'
  = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
  = stylesheet_link_tag 'print.css', :media => 'print'
  /[if lt IE 8]
    = stylesheet_link_tag 'ie.css', :media => 'screen, projection'
  = stylesheet_link_tag 'application.css', :media => 'screen, projection'
  = javascript_include_tag :defaults 
  = csrf_meta_tag 

  %body
    #wrapper		
      #header
      %h1#logo
        mewie.com blog
      %p.notice= flash[:notice]
      %p.error= flash[:error]
      #admin_bar 
        - if current_admin
          signed in as #{current_admin.name} 
          | 
          = link_to "sign out", sign_out_url
        -  else
          = link_to "sign in", sign_in_url
    #content
      = yield 

app/views/posts/_form.html.haml
= form_for @post do |f|
  -if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :post_time
    = f.datetime_select :post_time
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
= link_to 'new post', new_post_path, :class => "new_post_link" 

%ul
  - @posts.each do |post|
    %li
      %strong.index_title
        = post.title
      = post.post_time
      %span.post_description
        = truncate post.content, :length => 900
      = link_to 'Show', post
      = link_to 'Edit', edit_post_path(post)

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

.post_show

  .post_header

    .post_title
      = @post.title

  .post_time
    Posted on:
    = @post.post_time

  - if @post.admin
    .admin
      Posted by:
      = link_to @post.admin.name, @post.admin  

  .post_content
    = @post.content

.post_nav_links
  = link_to 'Edit', edit_post_path(@post)
  \|
  = link_to 'Back', posts_path